# Global Workspace credentials applied at deploy (upsert by mapName + keyName).
# Format: {mapName}.{keyName}.{property}=value
# mapName and keyName must not contain '.' (used as the key separator).
# Secrets are blank on export - fill target values before deploy.
# Delete any credential blocks you do not want managed at deploy time.


######################## Common.postman-GL ########################
Common.postman-GL.type=PASSWORD
Common.postman-GL.description=
Common.postman-GL.targetURL=https://postman-echo.com:443
Common.postman-GL.username=postman
Common.postman-GL.scope=GLOBAL
# password
Common.postman-GL.password=


######################## Common.OIC_Auth ########################
Common.OIC_Auth.type=OAUTH
Common.OIC_Auth.clientId=a184a6f5f7c3479d9813b307b68c5cca
Common.OIC_Auth.grantType=client_credentials
Common.OIC_Auth.authTokenUrl=https://idcs-75ed387a38c8444cba85ceb367ae6dff.identity.oraclecloud.com/oauth2/v1/token
Common.OIC_Auth.oauthIntegrationScope=https://F2A22485406D4A00A4610B5862A9F8EA.integration.us-ashburn-1.ocp.oraclecloud.com:443urn:opc:resource:consumer::all
Common.OIC_Auth.username=rajashekar.gaddi@flexagon.com
Common.OIC_Auth.description=
Common.OIC_Auth.targetURL=https://dev-v3-oic-idzor6zhmigm-ia.integration.us-ashburn-1.ocp.oraclecloud.com:443
Common.OIC_Auth.scope=GLOBAL
# secret
Common.OIC_Auth.secret=

